---
name: Hello World
version: dev
slug: hello_world
description: Minimal Hello World add-on
url: https://github.com/ImpThomasHein/home-assistant-fin-app
init: false
arch:
  - aarch64
  - amd64
  - armv7
options: {}
schema: {}
